package authorization

import "errors"

var (
	ErrInvalidAction            = errors.New("invalid authorization action")
	ErrInvalidRole              = errors.New("invalid authorization role")
	ErrInvalidScope             = errors.New("invalid authorization scope")
	ErrInvalidObjectKind        = errors.New("invalid authorization object kind")
	ErrInvalidMember            = errors.New("invalid authorization member")
	ErrInvalidMemberDirectory   = errors.New("invalid authorization member directory")
	ErrTooManyMembers           = errors.New("authorization member limit exceeded")
	ErrDuplicateMemberID        = errors.New("duplicate authorization member ID")
	ErrDuplicateLogicalIdentity = errors.New("duplicate authorization logical identity")
	ErrMemberNotFound           = errors.New("authorization member was not found")
	ErrInvalidPolicySpec        = errors.New("invalid authorization policy spec")
	ErrBindingsRequired         = errors.New("authorization policy bindings are required")
	ErrTooManyBindings          = errors.New("authorization policy binding limit exceeded")
	ErrInvalidBinding           = errors.New("invalid authorization policy binding")
	ErrInvalidBindingOrder      = errors.New("authorization policy bindings are not sorted")
	ErrDuplicateBinding         = errors.New("duplicate authorization policy binding")
	ErrEnvironmentNotFound      = errors.New("authorization environment was not found")
	ErrReferenceKindMismatch    = errors.New("authorization reference kind does not match")
	ErrWorkspaceMismatch        = errors.New("authorization workspace does not match")
	ErrPrincipalKindNotAllowed  = errors.New("authorization principal kind is not allowed")
	ErrInvalidPolicyRevision    = errors.New("invalid authorization policy revision")
	ErrInvalidPolicySet         = errors.New("invalid authorization policy set")
	ErrTooManyPolicies          = errors.New("authorization policy limit exceeded")
	ErrDuplicatePolicyID        = errors.New("duplicate authorization policy ID")
	ErrInvalidPolicyVersion     = errors.New("invalid authorization policy version")
	ErrInvalidInputDigest       = errors.New("invalid authorization input digest")
	ErrInvalidTarget            = errors.New("invalid authorization target")
	ErrInvalidInput             = errors.New("invalid authorization input")
	ErrInvalidDecision          = errors.New("invalid authorization decision")
	ErrDecisionTooLarge         = errors.New("canonical authorization decision exceeds size limit")
	ErrNonCanonicalDecision     = errors.New("authorization decision representation is not canonical")
	ErrSerializationForbidden   = errors.New("authorization serialization forbidden")
)
